//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MerchantService : DbContext
    {
        public MerchantService()
            : base("name=MerchantService")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_BusinessCategory> t_BusinessCategory { get; set; }
        public virtual DbSet<t_Department> t_Department { get; set; }
        public virtual DbSet<t_Office> t_Office { get; set; }
        public virtual DbSet<t_Staff> t_Staff { get; set; }
        public virtual DbSet<t_login_log> t_login_log { get; set; }
        public virtual DbSet<t_Transactions> t_Transactions { get; set; }
        public virtual DbSet<t_CardBin> t_CardBin { get; set; }
        public virtual DbSet<v_Transactions> v_Transactions { get; set; }
        public virtual DbSet<t_Merchant_Info> t_Merchant_Info { get; set; }
        public virtual DbSet<v_Merchant> v_Merchant { get; set; }
        public virtual DbSet<v_Staff> v_Staff { get; set; }
        public virtual DbSet<t_MStatus> t_MStatus { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
        public virtual DbSet<v_UserInfo> v_UserInfo { get; set; }
    }
}
