//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_login_log
    {
        public int login_logid { get; set; }
        public string login_user { get; set; }
        public Nullable<System.DateTime> date_time_log { get; set; }
        public Nullable<int> is_success { get; set; }
    
        public virtual t_Users t_Users { get; set; }
    }
}
