//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Merchant_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Merchant_Info()
        {
            this.t_Transactions = new HashSet<t_Transactions>();
        }
    
        public string MPU_Merchant_ID { get; set; }
        public string Merchant_Name { get; set; }
        public string Merchant_Address { get; set; }
        public string Merchant_Email { get; set; }
        public string Merchant_Phone { get; set; }
        public string Settlement_Acc { get; set; }
        public Nullable<double> MPURate { get; set; }
        public Nullable<double> JCBRate { get; set; }
        public Nullable<double> UPIRate { get; set; }
        public Nullable<double> OMPURate { get; set; }
        public Nullable<double> OJCBRate { get; set; }
        public Nullable<double> OUPIRate { get; set; }
        public Nullable<int> BusinessCategoryID { get; set; }
        public string SettAccountName { get; set; }
        public Nullable<int> MStatusID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
    
        public virtual t_BusinessCategory t_BusinessCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Transactions> t_Transactions { get; set; }
        public virtual t_Merchant_Info t_Merchant_Info1 { get; set; }
        public virtual t_Merchant_Info t_Merchant_Info2 { get; set; }
        public virtual t_MStatus t_MStatus { get; set; }
    }
}
