//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_MStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_MStatus()
        {
            this.t_Merchant_Info = new HashSet<t_Merchant_Info>();
        }
    
        public int MStatusID { get; set; }
        public string MStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Merchant_Info> t_Merchant_Info { get; set; }
    }
}
