//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Staff()
        {
            this.t_Users = new HashSet<t_Users>();
        }
    
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> OfficeID { get; set; }
    
        public virtual t_Department t_Department { get; set; }
        public virtual t_Office t_Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Users> t_Users { get; set; }
    }
}
