//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Transactions
    {
        public int TrxID { get; set; }
        public string RecordType { get; set; }
        public string CardNo { get; set; }
        public string CardType { get; set; }
        public string ProcessingCode { get; set; }
        public Nullable<double> TrxAmount { get; set; }
        public Nullable<double> SettAmount { get; set; }
        public string MPU_Merchant_ID { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public Nullable<double> MDRValue { get; set; }
        public Nullable<double> SettConversationRate { get; set; }
        public string CurrencyCode { get; set; }
        public string SettCurrencyCode { get; set; }
        public string TerminalID { get; set; }
        public string TRXRemark { get; set; }
        public Nullable<double> TRXMDRRate { get; set; }
    
        public virtual t_Merchant_Info t_Merchant_Info { get; set; }
    }
}
