//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Users()
        {
            this.t_login_log = new HashSet<t_login_log>();
        }
    
        public string UserID { get; set; }
        public string Passwd { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public Nullable<int> AdminLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_login_log> t_login_log { get; set; }
        public virtual t_Staff t_Staff { get; set; }
    }
}
