//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Merchant
    {
        public string MPU_Merchant_ID { get; set; }
        public string Merchant_Name { get; set; }
        public string Merchant_Address { get; set; }
        public string Merchant_Email { get; set; }
        public string Merchant_Phone { get; set; }
        public string Settlement_Acc { get; set; }
        public Nullable<double> MPURate { get; set; }
        public Nullable<double> JCBRate { get; set; }
        public Nullable<double> UPIRate { get; set; }
        public Nullable<double> OMPURate { get; set; }
        public Nullable<double> OJCBRate { get; set; }
        public Nullable<double> OUPIRate { get; set; }
        public Nullable<int> BusinessCategoryID { get; set; }
        public string BusinessCategory { get; set; }
        public string SettAccountName { get; set; }
        public Nullable<int> MStatusID { get; set; }
        public string MStatus { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
    }
}
