//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UserInfo
    {
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Department { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public string Office { get; set; }
        public string UserID { get; set; }
        public string Passwd { get; set; }
        public Nullable<int> AdminLogin { get; set; }
        public Nullable<int> UserLevel { get; set; }
    }
}
